### PR TITLE
add english code of conduct

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by robertkowalski** [comment]
wow awesome! just noticed you added so many commits! can we merge now? do you want me to add the last sentences of the cubaconf coc to the english coc?

**Comment by olemis** [comment]
Merge into master you mean ? Sure ! Please see my comment in #2 .

On 1/17/16, Robert Kowalski notifications@github.com wrote:

> wow awesome! just noticed you added so many commits! can we merge now? do
> you want me to add the last sentences of the cubaconf coc to the english
> coc?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodeschool/havana/pull/1#issuecomment-172404644

## 

Regards,

Olemis - @olemislc

Apache™ Bloodhound contributor
http://issues.apache.org/bloodhound
http://blood-hound.net

Brython committer
http://brython.info
http://github.com/brython-dev/brython

Blog ES: http://simelo-es.blogspot.com/
Blog EN: http://simelo-en.blogspot.com/

Featured article:

**Comment by robertkowalski** [comment]
i added the additions to the coc :)

**Comment by elMor3no** [comment]
Great job...

**Pull request merged**
